### ISSUE TITLE
[bug] --list doesn't work on AMD

### ISSUE THREAD

**Issue by jon-hotaisle** [kagehq/gpu-kill#2]
Two problems. 

1) amd doesn't work. 
2) this VM only has one GPU in it and you seem to be iterating over 11 of them?

<img width="1506" height="953" alt="Image" src="https://github.com/user-attachments/assets/bc71b9a1-8f6a-47db-bd34-443d39600db8" />

...

<img width="1511" height="591" alt="Image" src="https://github.com/user-attachments/assets/bb6fecf3-d4b8-4b73-bd3c-e52a4422d8d7" />

**Comment by dantelex** [comment]
> Two problems.
> 
> 1. amd doesn't work.
> 2. this VM only has one GPU in it and you seem to be iterating over 11 of them?
> 
> <img alt="Image" width="1506" height="953" src="https://private-user-images.githubusercontent.com/159235294/492054924-bc71b9a1-8f6a-47db-bd34-443d39600db8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0ODUxNzksIm5iZiI6MTc1ODQ4NDg3OSwicGF0aCI6Ii8xNTkyMzUyOTQvNDkyMDU0OTI0LWJjNzFiOWExLThmNmEtNDdkYi1iZDM0LTQ0M2QzOTYwMGRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyMVQyMDAxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWFlYWE5NTgwNTEzOThmZWNiYzdkMDZjZDgyOTI0MWM5MjAxMDA3ZGZhZWY5ODAxMjc5OWVkZGExZTVmNjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0lczBADXPP2rEH3hhyDqO8cMQllIAsJ2pPPnpZiUnCM">
> ...
> 
> <img alt="Image" width="1511" height="591" src="https://private-user-images.githubusercontent.com/159235294/492055005-bb6fecf3-d4b8-4b73-bd3c-e52a4422d8d7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0ODUxNzksIm5iZiI6MTc1ODQ4NDg3OSwicGF0aCI6Ii8xNTkyMzUyOTQvNDkyMDU1MDA1LWJiNmZlY2YzLWQ0YjgtNGI3My1iZDNjLWU1MmE0NDIyZDhkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyMVQyMDAxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTcyYjJiMmNmNmI3NzU4ZDRhZTJjYjEwNDg1MGU4ZWRhZjAwNTFiYzQ3ZmViNzVkMDE3MWZkOTEwYWY5ODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MvuimJeU_YzbLXAQSw7vqZMB1jXTuDgPfV2PVcKH8gs">

This should be fixed now @jon-hotaisle

**Comment by jon-hotaisle** [comment]
It works in that it doesn't error, but it is still not working.

<img width="1120" height="656" alt="Image" src="https://github.com/user-attachments/assets/50cdff4b-b648-40aa-b589-8662a60f2159" />

**Comment by dantelex** [comment]
> It works in that it doesn't error, but it is still not working.
> 
> <img alt="Image" width="1120" height="656" src="https://private-user-images.githubusercontent.com/159235294/492077263-50cdff4b-b648-40aa-b589-8662a60f2159.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg1MDMxODgsIm5iZiI6MTc1ODUwMjg4OCwicGF0aCI6Ii8xNTkyMzUyOTQvNDkyMDc3MjYzLTUwY2RmZjRiLWI2NDgtNDBhYS1iNTg5LTg2NjJhNjBmMjE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyMlQwMTAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTNiOTI0OWQ5ZjI3MmMwOTg2YzRmMGNlYjBlODdkYjVmMWRjMGU5ZDg5YzBhYzhkYmZmOGRmZWE3NTFhMmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iTcqghofmWYXxOFsMEYtcUEcYdlSE0sOD4GZHkIMQcM">

I just pushed a new build. This should work fine now. 

Should now show:

1 GPU instead of 4 (or 11)
38°C instead of 0°C
134W instead of 0W
285MB instead of 0MB
